#!/usr/bin/env python3
"""Export best trained PyTorch weights to ONNX and TFLite (GPU Delegate)."""

import hashlib
import json
import shutil
from pathlib import Path
from ultralytics import YOLO
import onnx2tf

BEST_PT = Path("runs/detect/models/locate_obstacle/runs/train/weights/best.pt")
OUTPUT_DIR = Path("models/locate_obstacle")
ASSETS_DIR = Path("android/app/src/main/assets/models")


def compute_sha256(filepath: Path) -> str:
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        while chunk := f.read(65536):
            h.update(chunk)
    return h.hexdigest()


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    dest_pt = OUTPUT_DIR / "locate_obstacle_best.pt"
    print(f"Copying {BEST_PT} -> {dest_pt}")
    shutil.copy2(BEST_PT, dest_pt)

    # 1. Export to ONNX
    print("Exporting PyTorch weights to ONNX...")
    model = YOLO(str(dest_pt))
    onnx_file = model.export(
        format="onnx",
        imgsz=640,
        opset=12,
        dynamic=False,
        simplify=False,
    )
    dest_onnx = Path(onnx_file)
    print(f"ONNX model ready at {dest_onnx} ({dest_onnx.stat().st_size} bytes)")

    # 2. Convert to TFLite via onnx2tf
    print("Converting ONNX to TFLite with GPU Delegate optimization...")
    tflite_out_dir = OUTPUT_DIR / "tflite_out"
    if tflite_out_dir.exists():
        shutil.rmtree(tflite_out_dir)

    onnx2tf.convert(
        input_onnx_file_path=str(dest_onnx),
        output_folder_path=str(tflite_out_dir),
        not_use_onnxsim=True,
        optimization_for_gpu_delegate=True,
        check_gpu_delegate_compatibility=True,
        output_integer_quantized_tflite=False,
        verbosity="info",
    )

    candidates = list(tflite_out_dir.glob("*.tflite"))
    print(f"Generated TFLite models: {[c.name for c in candidates]}")
    chosen_tflite = None
    for name in ["model_float16.tflite", "model_float32.tflite"]:
        p = tflite_out_dir / name
        if p.exists():
            chosen_tflite = p
            break
    if not chosen_tflite and candidates:
        chosen_tflite = candidates[0]

    assert chosen_tflite is not None, "No TFLite model generated by onnx2tf!"
    print(f"Chosen TFLite model: {chosen_tflite}")

    dest_asset = ASSETS_DIR / "locate_obstacle_model.tflite"
    shutil.copy2(chosen_tflite, dest_asset)
    tflite_sha = compute_sha256(dest_asset)

    print(f"\n--- SUCCESS ---")
    print(f"Deployed asset: {dest_asset}")
    print(f"File size: {dest_asset.stat().st_size} bytes")
    print(f"SHA-256: {tflite_sha}")

    metadata = {
        "model_file": dest_asset.name,
        "sha256": tflite_sha,
        "classes": ["keys", "wallet", "chair", "table", "couch", "door"],
        "num_classes": 6,
        "input_size": [1, 640, 640, 3],
    }
    meta_path = OUTPUT_DIR / "metadata.json"
    meta_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"Metadata saved to {meta_path}")


if __name__ == "__main__":
    main()
