#!/usr/bin/env python3
"""Train YOLOv8n on unified Locate + Obstacle dataset (keys, wallet, chair, table, couch, door).

Exports:
  1. PyTorch weights (.pt) -> models/locate_obstacle/locate_obstacle_best.pt
  2. ONNX model (.onnx) -> models/locate_obstacle/locate_obstacle_best.onnx
  3. TFLite FP16 GPU Delegate model (.tflite) via onnx2tf ->
     android/app/src/main/assets/models/locate_obstacle_model.tflite
"""

import hashlib
import os
import shutil
import sys
from pathlib import Path
import torch
from ultralytics import YOLO
import onnx2tf

DATA_YAML = Path("datasets/locate_obstacle_combined/data.yaml")
OUTPUT_DIR = Path("models/locate_obstacle")
ASSETS_DIR = Path("android/app/src/main/assets/models")


def compute_sha256(filepath: Path) -> str:
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        while chunk := f.read(65536):
            h.update(chunk)
    return h.hexdigest()


def main():
    print(f"CUDA available: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"Device: {torch.cuda.get_device_name(0)}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    # Use pretrained yolov8n or existing weights
    base_model = "yolov8n.pt"
    if Path("models/locate/locate_best.pt").exists():
        print("Using models/locate/locate_best.pt as starting weights for fine-tuning...")
        base_model = "models/locate/locate_best.pt"

    model = YOLO(base_model)

    print("\n--- Starting YOLOv8n Fine-Tuning ---")
    results = model.train(
        data=str(DATA_YAML.resolve()),
        epochs=12,
        imgsz=640,
        batch=16,
        device="cpu",
        project=str(OUTPUT_DIR / "runs"),
        name="train",
        exist_ok=True,
        workers=4,
        seed=42,
        plots=False,
        save=True,
        val=True,
    )

    best_pt = OUTPUT_DIR / "runs" / "train" / "weights" / "best.pt"
    dest_pt = OUTPUT_DIR / "locate_obstacle_best.pt"
    if best_pt.exists():
        shutil.copy2(best_pt, dest_pt)
        print(f"\nBest PyTorch weights saved to {dest_pt}")
    else:
        last_pt = OUTPUT_DIR / "runs" / "train" / "weights" / "last.pt"
        shutil.copy2(last_pt, dest_pt)
        print(f"\nLast PyTorch weights saved to {dest_pt}")

    # Export to ONNX
    print("\n--- Exporting to ONNX ---")
    export_model = YOLO(str(dest_pt))
    onnx_file = export_model.export(
        format="onnx",
        imgsz=640,
        opset=12,
        dynamic=False,
        simplify=False,
    )
    dest_onnx = OUTPUT_DIR / "locate_obstacle_best.onnx"
    shutil.copy2(onnx_file, dest_onnx)
    print(f"ONNX model saved to {dest_onnx}")

    # Convert to TFLite via onnx2tf for GPU Delegate
    print("\n--- Converting ONNX to TFLite via onnx2tf ---")
    tflite_out_dir = OUTPUT_DIR / "tflite_out"
    if tflite_out_dir.exists():
        shutil.rmtree(tflite_out_dir)

    onnx2tf.convert(
        input_onnx_file_path=str(dest_onnx),
        output_folder_path=str(tflite_out_dir),
        not_use_onnxsim=True,
        optimization_for_gpu_delegate=True,
        check_gpu_delegate_compatibility=True,
        output_integer_quantized_tflite=False,
        verbosity="info",
    )

    # Find converted tflite (model_float16.tflite or model_float32.tflite)
    candidates = list(tflite_out_dir.glob("*.tflite"))
    print(f"Generated TFLite models: {[c.name for c in candidates]}")
    chosen_tflite = None
    for name in ["model_float16.tflite", "model_float32.tflite"]:
        p = tflite_out_dir / name
        if p.exists():
            chosen_tflite = p
            break
    if not chosen_tflite and candidates:
        chosen_tflite = candidates[0]

    assert chosen_tflite is not None, "No TFLite model generated by onnx2tf!"
    print(f"Chosen TFLite: {chosen_tflite}")

    # Copy to Android assets
    dest_asset = ASSETS_DIR / "locate_obstacle_model.tflite"
    shutil.copy2(chosen_tflite, dest_asset)
    tflite_sha = compute_sha256(dest_asset)
    print(f"\nSuccessfully deployed to {dest_asset}")
    print(f"File size: {dest_asset.stat().st_size} bytes")
    print(f"SHA-256: {tflite_sha}")

    # Write metadata
    metadata = {
        "model_file": dest_asset.name,
        "sha256": tflite_sha,
        "classes": ["keys", "wallet", "chair", "table", "couch", "door"],
        "num_classes": 6,
        "input_size": [1, 640, 640, 3],
    }
    import json
    meta_path = OUTPUT_DIR / "metadata.json"
    meta_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"Metadata saved to {meta_path}")


if __name__ == "__main__":
    main()
